import { ChallengeDifficulty } from '@prisma/client';

/**
 * The Vital30 starter catalog — 6 categories and 42 challenges (7 per
 * category). This is the single source of truth shared by both seed scripts:
 *
 *   - `seed.ts`          — destructive full reset for LOCAL dev (wipes the DB,
 *                          recreates a super admin, then loads this catalog).
 *   - `seed-catalog.ts`  — non-destructive UPSERT for PRODUCTION (loads/refreshes
 *                          this catalog without touching any user data).
 *
 * Keep all catalog content here so the two scripts can never drift apart.
 */

export interface SeedCategory {
  name: string;
  slug: string;
  description: string;
}

export interface SeedChallenge {
  title: string;
  slug: string;
  shortDescription: string;
  description: string;
  durationDays: number;
  difficulty: ChallengeDifficulty;
  dailyTask: string;
  benefits: string[];
  safetyNote: string;
  isPopular: boolean;
  isRecommended: boolean;
  /** Maps to a `SeedCategory.slug`; resolved to a real category id at seed time. */
  categoryIdKey: string;
}

export const categoriesData: SeedCategory[] = [
  {
    name: 'Diet & Nutrition',
    slug: 'diet-nutrition',
    description: 'Fuel your body with wholesome, nutrient-dense foods and clean hydration habits.',
  },
  {
    name: 'Fitness & Movement',
    slug: 'fitness-movement',
    description: 'Strengthen your heart and body through daily exercise and functional mobility.',
  },
  {
    name: 'Mental Wellness',
    slug: 'mental-wellness',
    description: 'Calm your mind, improve focus, and develop emotional resilience.',
  },
  {
    name: 'Sleep & Recovery',
    slug: 'sleep-recovery',
    description: 'Optimize your rest periods to promote cell repair and high daytime energy.',
  },
  {
    name: 'Break Bad Habits',
    slug: 'break-bad-habits',
    description: 'Overcome self-limiting habits, mindless scrolling, and unproductive routines.',
  },
  {
    name: 'Family Wellness',
    slug: 'family-wellness',
    description: 'Connect with loved ones and establish health-focused group activities.',
  },
];

export const challengesData: SeedChallenge[] = [
  // --- Category: Diet & Nutrition ---
  {
    title: 'No Refined Sugar',
    slug: 'no-refined-sugar',
    shortDescription: 'Cut out all processed sugars and artificial sweeteners.',
    description: 'Remove refined sugars from your meals and drinks. Focus on getting clean, sustained energy from fruits, vegetables, and complex carbohydrates.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.MEDIUM,
    dailyTask: 'Check labels and consume 0 grams of added or refined sugars today.',
    benefits: ['Reduced inflammation', 'Stabilized insulin and blood sugar', 'Fewer sweet cravings', 'Improved cognitive clarity'],
    safetyNote: 'If you have type 1 or type 2 diabetes, consult your doctor before modifying sugar intake.',
    isPopular: true,
    isRecommended: true,
    categoryIdKey: 'diet-nutrition',
  },
  {
    title: 'Hydration Hero',
    slug: 'hydration-hero',
    shortDescription: 'Drink 3 liters of pure water every day.',
    description: 'Proper hydration is vital for every cell in your body. Carry a water bottle and track your intake to reach 3 liters daily.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.BEGINNER,
    dailyTask: 'Drink a minimum of 3 liters (approx. 100 oz) of water.',
    benefits: ['Clearer skin texture', 'Boosted physical performance', 'Reduced headaches', 'Enhanced kidney filtration'],
    safetyNote: 'Individuals with congestive heart failure or kidney disease should adjust fluid goals with their physician.',
    isPopular: true,
    isRecommended: false,
    categoryIdKey: 'diet-nutrition',
  },
  {
    title: 'Veggie Power',
    slug: 'veggie-power',
    shortDescription: 'Include three servings of vegetables in your daily meals.',
    description: 'Boost your vitamins, fiber, and phytonutrients by adding fresh or steamed vegetables to at least two meals today.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.EASY,
    dailyTask: 'Eat 3 full servings (approx. 3 cups) of vegetables.',
    benefits: ['High intake of dietary fiber', 'Antioxidant cell protection', 'Better gut microbiome health', 'Natural weight management'],
    safetyNote: 'Wash all vegetables thoroughly before consumption to eliminate surface contaminants.',
    isPopular: false,
    isRecommended: true,
    categoryIdKey: 'diet-nutrition',
  },
  {
    title: 'Mindful Chewing',
    slug: 'mindful-chewing',
    shortDescription: 'Chew every bite of your food 20 times.',
    description: 'Digestion starts in the mouth. Prevent overeating and improve gut absorption by thoroughly chewing every bite before swallowing.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.EASY,
    dailyTask: 'Chew all solid food particles at least 20 times per mouthful.',
    benefits: ['Optimized enzymatic breakdown', 'Alleviated bloating and gas', 'Increased satiety awareness', 'Better food appreciation'],
    safetyNote: 'Take small, manageable bites to avoid choking hazards.',
    isPopular: false,
    isRecommended: false,
    categoryIdKey: 'diet-nutrition',
  },
  {
    title: 'Intermittent Fasting 16:8',
    slug: 'intermittent-fasting-16-8',
    shortDescription: 'Limit food consumption to an 8-hour daily window.',
    description: 'Give your digestive system a long break. Restrict eating to an 8-hour window (e.g., 12:00 PM to 8:00 PM) and fast for the remaining 16 hours.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.HARD,
    dailyTask: 'Fast for 16 consecutive hours, consuming only water, black coffee, or plain tea.',
    benefits: ['Cellular autophagy activation', 'Enhanced metabolic flexibility', 'Promoted fat oxidation', 'Improved longevity markers'],
    safetyNote: 'Fasting is not recommended for pregnant women, teenagers, or anyone with a history of disordered eating.',
    isPopular: true,
    isRecommended: false,
    categoryIdKey: 'diet-nutrition',
  },
  {
    title: 'Home Cooked Only',
    slug: 'home-cooked-only',
    shortDescription: 'Avoid restaurants, fast food, and highly processed takeout.',
    description: 'Control exactly what goes into your body. Prepare all meals, snacks, and beverages at home using whole, fresh ingredients.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.MEDIUM,
    dailyTask: 'Cook or prepare all consumed meals at home today.',
    benefits: ['Strict control over sodium and seed oils', 'Saves money', 'Enhanced culinary skills', 'Greater awareness of nutrition'],
    safetyNote: 'Ensure safe meat and poultry cooking temperatures are reached during food preparation.',
    isPopular: false,
    isRecommended: true,
    categoryIdKey: 'diet-nutrition',
  },
  {
    title: 'High-Protein Breakfast Starter',
    slug: 'high-protein-breakfast',
    shortDescription: 'Eat a high-protein, zero-sugar breakfast within 90 minutes of waking.',
    description: 'Kickstart your metabolism and stabilize your energy. Consume at least 30 grams of clean protein in your first meal, skipping sugary cereals or pastries.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.EASY,
    dailyTask: 'Eat a breakfast containing 30g+ of protein (e.g., eggs, Greek yogurt, or protein shake).',
    benefits: ['Reduced mid-day cravings', 'Stabilized blood glucose curve', 'Preserved skeletal muscle mass', 'Sustained cognitive focus'],
    safetyNote: 'Adjust protein sources if you have diagnosed chronic kidney conditions.',
    isPopular: true,
    isRecommended: true,
    categoryIdKey: 'diet-nutrition',
  },

  // --- Category: Fitness & Movement ---
  {
    title: 'Daily 10k Steps',
    slug: 'daily-10k-steps',
    shortDescription: 'Walk at least 10,000 steps every single day.',
    description: 'Combat sedentary modern life. Increase non-exercise activity thermogenesis (NEAT) by logging 10,000 steps on your tracker.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.EASY,
    dailyTask: 'Walk a total of 10,000 steps.',
    benefits: ['Strengthened cardiovascular system', 'Increased daily caloric burn', 'Improved joint health', 'Natural mood elevator'],
    safetyNote: 'Wear supportive athletic shoes to avoid foot pain or blisters.',
    isPopular: true,
    isRecommended: true,
    categoryIdKey: 'fitness-movement',
  },
  {
    title: 'Core Strength Builder',
    slug: 'core-strength-builder',
    shortDescription: 'Execute a daily 10-minute core workout.',
    description: 'A strong core stabilizes your entire skeleton. Commit to 10 minutes of targeted abdominal and lower back exercises daily.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.MEDIUM,
    dailyTask: 'Perform 10 minutes of core exercises (planks, bird-dogs, dead-bugs).',
    benefits: ['Reduced lower back strain', 'Enhanced athletic power', 'Better standing posture', 'Improved balance and coordination'],
    safetyNote: 'Stop immediately if you experience sharp or shooting lower back discomfort.',
    isPopular: false,
    isRecommended: true,
    categoryIdKey: 'fitness-movement',
  },
  {
    title: 'Morning Mobility Stretch',
    slug: 'morning-mobility-stretch',
    shortDescription: 'Spend 15 minutes stretching your muscles upon waking.',
    description: 'Start your morning with fluidity. Loosen tight hips, hamstrings, and shoulders with a dynamic mobility sequence.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.BEGINNER,
    dailyTask: 'Complete 15 minutes of full-body dynamic stretching.',
    benefits: ['Increased range of joint motion', 'Stimulated early morning blood flow', 'Alleviated muscular stiffness', 'Enhanced nervous system readiness'],
    safetyNote: 'Perform gentle, slow stretches; never bounce or force a joint past its natural range.',
    isPopular: true,
    isRecommended: true,
    categoryIdKey: 'fitness-movement',
  },
  {
    title: 'Couch to 5k Runner',
    slug: 'couch-to-5k-runner',
    shortDescription: 'Jog or briskly walk for 20 minutes.',
    description: 'Build your cardiovascular stamina. Walk or jog consistently for 20 minutes to transition toward running a 5k.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.MEDIUM,
    dailyTask: 'Perform a 20-minute walk/run interval session today.',
    benefits: ['Enhanced aerobic capacity', 'Lower resting heart rate', 'Improved bone density', 'Greater cardiovascular endurance'],
    safetyNote: 'If you have existing knee or hip osteoarthritis, check with a physical therapist first.',
    isPopular: true,
    isRecommended: false,
    categoryIdKey: 'fitness-movement',
  },
  {
    title: 'Strength Training Basics',
    slug: 'strength-training-basics',
    shortDescription: 'Complete a standard bodyweight routine.',
    description: 'Build functional muscle mass. Perform fundamental bodyweight movements to improve core strength and muscle tone.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.MEDIUM,
    dailyTask: 'Complete 20 squats, 15 pushups, and a 1-minute plank today.',
    benefits: ['Preserved muscle mass', 'Increased bone density', 'Optimized resting metabolic rate', 'Better posture'],
    safetyNote: 'Focus on perfect form rather than speed. Modify pushups to knee pushups if necessary.',
    isPopular: false,
    isRecommended: true,
    categoryIdKey: 'fitness-movement',
  },
  {
    title: 'Stair Climber Challenge',
    slug: 'stair-climber',
    shortDescription: 'Take the stairs instead of elevators or escalators.',
    description: 'Turn your commute into a workout. Pledge to take the stairs for every journey under 5 flights throughout the day.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.EASY,
    dailyTask: 'Climb a total of 10 flights of stairs today.',
    benefits: ['Targeted glute and quad strengthening', 'Spikes cardiovascular efficiency', 'Zero gym equipment needed', 'Builds lower body power'],
    safetyNote: 'Use handrails for balance when walking on steep or wet staircases.',
    isPopular: false,
    isRecommended: false,
    categoryIdKey: 'fitness-movement',
  },
  {
    title: 'Yoga Devotee',
    slug: 'yoga-devotee',
    shortDescription: 'Perform 15 minutes of slow-flow yoga.',
    description: 'Calm your mind while enhancing flexibility. Practice 15 minutes of structured, breath-linked yoga poses daily.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.BEGINNER,
    dailyTask: 'Complete a 15-minute yoga session (Vinyasa or Yin).',
    benefits: ['Improved flexibility and posture', 'Lowered stress hormones', 'Better mind-body awareness', 'Enhanced muscular recovery'],
    safetyNote: 'Never force a yoga pose that causes pinching or joint pain.',
    isPopular: false,
    isRecommended: false,
    categoryIdKey: 'fitness-movement',
  },

  // --- Category: Mental Wellness ---
  {
    title: 'Daily Gratitude Journal',
    slug: 'daily-gratitude-journal',
    shortDescription: 'Write down three unique things you are grateful for.',
    description: 'Shift your mindset toward abundance. Every morning or evening, write down three specific, detailed things that brought you joy today.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.BEGINNER,
    dailyTask: 'Write 3 unique gratitude points in a journal.',
    benefits: ['Rewires brain to focus on positives', 'Decreases anxiety and self-doubt', 'Improves relationship satisfaction', 'Enables deeper nightly sleep'],
    safetyNote: 'Focus on authentic, small details rather than broad generalizations.',
    isPopular: true,
    isRecommended: true,
    categoryIdKey: 'mental-wellness',
  },
  {
    title: 'Mindful Meditation',
    slug: 'mindful-meditation',
    shortDescription: 'Meditate quietly for 10 minutes.',
    description: 'Cultivate presence. Sit in a comfortable position, close your eyes, and focus strictly on your breathing, letting stray thoughts pass.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.MEDIUM,
    dailyTask: 'Sit in silent or guided meditation for 10 minutes today.',
    benefits: ['Enriched emotional regulation', 'Better attention span and focus', 'Decreased amygdala hyper-reactivity', 'Reduced subjective stress levels'],
    safetyNote: 'If sitting upright is painful, it is acceptable to lie down, provided you remain awake.',
    isPopular: true,
    isRecommended: true,
    categoryIdKey: 'mental-wellness',
  },
  {
    title: 'Digital Detox Evening',
    slug: 'digital-detox-evening',
    shortDescription: 'Turn off all screens 1 hour before bedtime.',
    description: 'Protect your focus. Turn off televisions, computers, tablets, and phones 60 minutes before sleeping to allow natural melatonin production.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.MEDIUM,
    dailyTask: 'Power down all screen-based devices 1 hour before sleeping.',
    benefits: ['Deeper restorative sleep stages', 'Lower blue-light brain stimulation', 'Time for reading or conversation', 'Reduced evening anxiety'],
    safetyNote: 'Inform family or roommates of your screen-free timeframe in case of emergencies.',
    isPopular: true,
    isRecommended: false,
    categoryIdKey: 'mental-wellness',
  },
  {
    title: 'Deep Breathing Breaks',
    slug: 'deep-breathing-breaks',
    shortDescription: 'Perform three 2-minute conscious breathing sessions.',
    description: 'Regulate your autonomic nervous system. Take three short breaks during the day to practice slow diaphragmatic breathing.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.BEGINNER,
    dailyTask: 'Complete three separate 2-minute sessions of 4-7-8 breathing.',
    benefits: ['Activates parasympathetic relaxation', 'Lowers acute blood pressure spikes', 'Alleviates shoulder and chest tension', 'Increases blood oxygen saturation'],
    safetyNote: 'If you feel lightheaded, return immediately to your normal breathing cadence.',
    isPopular: false,
    isRecommended: true,
    categoryIdKey: 'mental-wellness',
  },
  {
    title: 'Read 10 Pages',
    slug: 'read-10-pages',
    shortDescription: 'Read 10 pages of a non-fiction book.',
    description: 'Acquire new knowledge and exercise your brain. Substitute social media scrolling with 10 pages of physical book reading.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.EASY,
    dailyTask: 'Read at least 10 pages of a non-fiction or educational book.',
    benefits: ['Stimulated cognitive pathways', 'Continuous learning and skill building', 'Improved vocabulary and focus', 'Calms the active mind before sleep'],
    safetyNote: 'Ensure adequate lighting while reading to minimize eye strain.',
    isPopular: false,
    isRecommended: true,
    categoryIdKey: 'mental-wellness',
  },
  {
    title: 'Nature Walk Connection',
    slug: 'nature-walk-connection',
    shortDescription: 'Walk in a green space for 20 minutes without headphones.',
    description: 'Connect with your natural surroundings. Spend 20 minutes walking in a park, forest, or beach, actively listening to the environment.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.EASY,
    dailyTask: 'Walk in a natural outdoor environment for 20 minutes without devices.',
    benefits: ['Reduces systemic cortisol levels', 'Boosts creativity and problem solving', 'Restores sensory focus', 'Increases Vitamin D synthesis'],
    safetyNote: 'Be aware of your physical surroundings, wildlife, and path conditions.',
    isPopular: false,
    isRecommended: false,
    categoryIdKey: 'mental-wellness',
  },
  {
    title: 'Mirror Positive Affirmations',
    slug: 'positive-affirmations',
    shortDescription: 'Speak three positive affirmations aloud in front of a mirror.',
    description: 'Reprogram self-limiting beliefs. Stand tall before a mirror every morning, make eye contact with yourself, and speak three constructive affirmations.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.BEGINNER,
    dailyTask: 'Spend 2 minutes speaking positive affirmations aloud today.',
    benefits: ['Boosts self-efficacy and belief', 'Replaces negative self-talk patterns', 'Enhances speaking confidence', 'Reduces morning anxiety'],
    safetyNote: 'Choose phrases that align with your genuine values and aspirations.',
    isPopular: false,
    isRecommended: false,
    categoryIdKey: 'mental-wellness',
  },

  // --- Category: Sleep & Recovery ---
  {
    title: 'Early Bird Bedtime',
    slug: 'early-bird-bedtime',
    shortDescription: 'Be in bed with lights out by 10:30 PM.',
    description: 'Sync with your natural circadian rhythm. Prepare your body for rest and aim to fall asleep by 10:30 PM to optimize deep sleep cycles.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.MEDIUM,
    dailyTask: 'Turn off all room lights and lie in bed by 10:30 PM.',
    benefits: ['Optimized release of human growth hormone', 'Waking up refreshed without alarms', 'Consistent circadian alignment', 'Enhanced memory consolidation'],
    safetyNote: 'If you work night shifts, adjust your target time to maintain a consistent 8-hour sleep block.',
    isPopular: true,
    isRecommended: true,
    categoryIdKey: 'sleep-recovery',
  },
  {
    title: 'No Afternoon Caffeine',
    slug: 'no-afternoon-caffeine',
    shortDescription: 'Avoid all caffeinated beverages after 2:00 PM.',
    description: 'Caffeine has a half-life of up to 6 hours. Prevent caffeine from blocking adenosine receptors in your brain at night by stopping intake early.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.EASY,
    dailyTask: 'Consume zero coffee, energy drinks, black tea, or soda after 2:00 PM today.',
    benefits: ['Easier sleep onset', 'Increased percentage of deep sleep', 'Fewer nighttime wakeups', 'Reduced morning dependency on caffeine'],
    safetyNote: 'Be prepared for mild withdrawal headaches in the first few days if caffeine intake was heavy.',
    isPopular: true,
    isRecommended: true,
    categoryIdKey: 'sleep-recovery',
  },
  {
    title: 'Cold Shower Recovery',
    slug: 'cold-shower-recovery',
    shortDescription: 'Finish your daily shower with 1 minute of cold water.',
    description: 'Stimulate cellular resilience. At the end of your warm shower, turn the dial completely to cold and focus on slow, controlled breathing for 60 seconds.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.HARD,
    dailyTask: 'End your daily shower with 60 seconds of purely cold water.',
    benefits: ['Spikes dopamine and alert levels', 'Vasoconstriction reduces muscle soreness', 'Builds high mental resilience', 'Improves skin and hair moisture retention'],
    safetyNote: 'Avoid cold plunges/showers if you have diagnosed cardiac arrhythmias or serious heart conditions.',
    isPopular: true,
    isRecommended: false,
    categoryIdKey: 'sleep-recovery',
  },
  {
    title: 'Sleep Sanctuary Setup',
    slug: 'sleep-sanctuary',
    shortDescription: 'Sleep in a dark, cool, and silent room.',
    description: 'Maximize sleep efficiency. Optimize your environment by utilizing blackout curtains, earplugs, or white noise, and lowering the thermostat to 68°F (20°C).',
    durationDays: 30,
    difficulty: ChallengeDifficulty.EASY,
    dailyTask: 'Ensure bedroom is blacked out and temperature is set cool tonight.',
    benefits: ['Reduced sleep micro-arousals', 'Deep, uninterrupted REM sleep', 'Faster core body temperature drop', 'Decreased sweating during rest'],
    safetyNote: 'Maintain a safe pathway in the bedroom in case you need to wake up in the dark.',
    isPopular: false,
    isRecommended: true,
    categoryIdKey: 'sleep-recovery',
  },
  {
    title: 'Wind-down Brain Dump',
    slug: 'wind-down-brain-dump',
    shortDescription: 'Write tomorrow’s to-do list before bedtime.',
    description: 'Clear your mind of bedtime anxiety. Spend 5 minutes writing down outstanding tasks or worries to offload mental strain before sleep.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.BEGINNER,
    dailyTask: 'Write out your thoughts and to-do list for tomorrow in a notebook.',
    benefits: ['Reduced sleep latency', 'Minimizes tossing and turning', 'Enhanced proactive morning focus', 'Decreased sleep-related worry'],
    safetyNote: 'Do this on physical paper rather than on a bright mobile screen.',
    isPopular: false,
    isRecommended: false,
    categoryIdKey: 'sleep-recovery',
  },
  {
    title: 'Blue Light Blockout',
    slug: 'blue-light-blockout',
    shortDescription: 'Wear blue-light blocking glasses or filter screens 2 hours before bed.',
    description: 'Preserve natural melatonin. Block the sleep-disrupting blue spectrum from light bulbs and screens by using specialized eyewear or device filters.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.BEGINNER,
    dailyTask: 'Wear blue-light blockers or enable strict orange filters on screens after 8 PM.',
    benefits: ['Maintains natural melatonin release', 'Alleviates digital eye strain', 'Improves evening sleepiness cues', 'Prevents sleep cycle delays'],
    safetyNote: 'Do not wear tinted glasses while operating machinery or driving.',
    isPopular: false,
    isRecommended: false,
    categoryIdKey: 'sleep-recovery',
  },
  {
    title: 'Post-Workout Stretch',
    slug: 'post-workout-stretch',
    shortDescription: 'Perform 10 minutes of active stretching after exercise.',
    description: 'Accelerate muscular recovery. Take 10 minutes to stretch target muscles directly after completing any physical workout.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.EASY,
    dailyTask: 'Spend 10 minutes stretching the muscle groups worked today.',
    benefits: ['Faster clearance of metabolic waste', 'Restored resting muscle length', 'Reduced Delayed Onset Muscle Soreness (DOMS)', 'Better joint alignment'],
    safetyNote: 'Only stretch warm muscles. Avoid forcing a joint beyond a gentle pulling sensation.',
    isPopular: false,
    isRecommended: true,
    categoryIdKey: 'sleep-recovery',
  },

  // --- Category: Break Bad Habits ---
  {
    title: 'Scroll-Free Social Media',
    slug: 'scroll-free-social-media',
    shortDescription: 'Limit total social media scrolling to 15 minutes daily.',
    description: 'Break free from dopamine loops. Restrict passive scrolling on Instagram, TikTok, or Twitter to a strict 15-minute maximum window.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.HARD,
    dailyTask: 'Limit social media screen time to 15 minutes or less today.',
    benefits: ['Reclaimed productive hours', 'Reduced social comparison anxiety', 'Restored natural attention spans', 'Lowered evening brain fatigue'],
    safetyNote: 'Use built-in app screen timers or block apps entirely to enforce this.',
    isPopular: true,
    isRecommended: true,
    categoryIdKey: 'break-bad-habits',
  },
  {
    title: 'No Late-Night Snacking',
    slug: 'no-late-night-snacking',
    shortDescription: 'Stop eating completely after 8:00 PM.',
    description: 'Prevent acid reflux and sleep disruption. Close your kitchen and commit to drinking only water or non-caffeinated herbal teas after 8:00 PM.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.MEDIUM,
    dailyTask: 'Consume no food or caloric liquids after 8:00 PM today.',
    benefits: ['Reduced evening calorie bloat', 'Deeper sleep quality', 'Improved morning appetite and digestion', 'Aids in steady fat loss'],
    safetyNote: 'Ensure you consume sufficient nutrients and calories during daylight hours.',
    isPopular: true,
    isRecommended: true,
    categoryIdKey: 'break-bad-habits',
  },
  {
    title: 'Zero Alcohol Month',
    slug: 'zero-alcohol',
    shortDescription: 'Refrain from drinking all alcoholic beverages.',
    description: 'Reset your body and liver health. Remove wine, beer, spirits, and mixed drinks entirely from your social routines.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.HARD,
    dailyTask: 'Consume 0 units of alcohol today.',
    benefits: ['Rejuvenated liver enzyme profile', 'Enhanced deep sleep architecture', 'Lower systemic inflammation', 'Clearer mental acuity'],
    safetyNote: 'If you have a history of severe clinical alcohol dependence, consult a medical detox specialist first.',
    isPopular: true,
    isRecommended: false,
    categoryIdKey: 'break-bad-habits',
  },
  {
    title: 'No Complaining Challenge',
    slug: 'no-complaining',
    shortDescription: 'Spend 24 hours without complaining or criticizing.',
    description: 'Develop a proactive mindset. If you catch yourself complaining about situations or others, pivot immediately to a solutions-focused response.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.HARD,
    dailyTask: 'Go the entire day without uttering a single complaint.',
    benefits: ['Improved workplace and home relationships', 'Reduces subconscious stress response', 'Increases constructive problem-solving skills', 'More pleasant social interactions'],
    safetyNote: 'Do not suppress authentic feelings; instead, frame issues constructively.',
    isPopular: false,
    isRecommended: true,
    categoryIdKey: 'break-bad-habits',
  },
  {
    title: 'Zero Impulse Purchasing',
    slug: 'zero-impulse-purchases',
    shortDescription: 'Do not buy non-essential retail items.',
    description: 'Practice consumer discipline. Delay non-essential purchases (clothes, gadgets, decor) for 30 days, placing items on a 30-day cooling list instead.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.MEDIUM,
    dailyTask: 'Buy only essential groceries, medicine, and utilities today.',
    benefits: ['Substantial financial savings', 'Breaks dopamine-driven purchasing cycles', 'Fewer cluttered living spaces', 'Greater appreciation for items owned'],
    safetyNote: 'Do not compromise on emergency healthcare or essential structural repairs.',
    isPopular: false,
    isRecommended: false,
    categoryIdKey: 'break-bad-habits',
  },
  {
    title: 'Reduce Screen Time',
    slug: 'reduce-screen-time',
    shortDescription: 'Reduce daily screen time by 1 hour.',
    description: 'Unplug and live. Analyze your phone screen time statistics and commit to reducing active screen hours by 60 minutes.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.MEDIUM,
    dailyTask: 'Decrease total non-work screen time by 1 hour today.',
    benefits: ['Alleviated eye strain and dry eyes', 'More time for offline hobbies', 'Increased physical presence', 'Lower mental fatigue'],
    safetyNote: 'Replace screen time with active movement, social connection, or reading.',
    isPopular: false,
    isRecommended: true,
    categoryIdKey: 'break-bad-habits',
  },
  {
    title: 'Fast Food Ban',
    slug: 'fast-food-ban',
    shortDescription: 'Avoid all fast food chains and deep-fried items.',
    description: 'Cleanse your digestive tract. Eliminate highly processed deep-fried burgers, fries, and greasy fast foods that contain industrial trans fats.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.MEDIUM,
    dailyTask: 'Avoid eating at fast food restaurants or consuming deep-fried snacks today.',
    benefits: ['Improved arterial and cardiovascular health', 'Fewer digestive upsets and gas', 'Higher energy from whole foods', 'Lower sodium retention'],
    safetyNote: 'Prepare healthy whole-food snacks at home to manage sudden hunger pangs.',
    isPopular: false,
    isRecommended: false,
    categoryIdKey: 'break-bad-habits',
  },

  // --- Category: Family Wellness ---
  {
    title: 'Family Dinner Table',
    slug: 'family-dinner-table',
    shortDescription: 'Have dinner together without any phones at the table.',
    description: 'Strengthen family bonds. Gather around the dining table for dinner with a strict "zero phone/screens" rule for all members.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.EASY,
    dailyTask: 'Eat a distraction-free family dinner at the table.',
    benefits: ['Enhanced interpersonal communication', 'Mindful eating patterns in children', 'Stronger family connectivity', 'Deeper sharing of daily stories'],
    safetyNote: 'Create a designated phone basket located away from the dining table.',
    isPopular: true,
    isRecommended: true,
    categoryIdKey: 'family-wellness',
  },
  {
    title: 'Active Family Weekend',
    slug: 'active-family-weekend',
    shortDescription: 'Plan and execute a weekly outdoor family activity.',
    description: 'Build active memories. Get the entire family outdoors for a weekly bike ride, nature hike, or park game (at least 60 minutes).',
    durationDays: 30,
    difficulty: ChallengeDifficulty.EASY,
    dailyTask: 'Spend active time outdoors with family (or check-in with a family fitness goal).',
    benefits: ['Healthy habit modeling for children', 'Shared active cardiovascular movement', 'Vitamin D exposure', 'Saves money on commercial entertainment'],
    safetyNote: 'Select outdoor paths that are suitable for all age ranges in the group.',
    isPopular: true,
    isRecommended: true,
    categoryIdKey: 'family-wellness',
  },
  {
    title: 'Weekly Board Game Night',
    slug: 'weekly-board-game-night',
    shortDescription: 'Play a board game or puzzle together as a family.',
    description: 'Promote screen-free play. Schedule a weekly game night to engage in cognitive, collaborative, and fun board games or puzzles.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.BEGINNER,
    dailyTask: 'Spend at least 30 minutes playing a collaborative board game/puzzle today.',
    benefits: ['Promotes cognitive strategy in youth', 'Breaks screen addiction habits', 'Enables laughter and bonding', 'Fosters good sportsmanship'],
    safetyNote: 'Ensure board game parts are safe and do not present choking hazards for toddlers.',
    isPopular: false,
    isRecommended: true,
    categoryIdKey: 'family-wellness',
  },
  {
    title: 'Acts of Family Kindness',
    slug: 'acts-of-family-kindness',
    shortDescription: 'Perform one daily small act of kindness for a family member.',
    description: 'Cultivate gratitude at home. Do a chore, leave a positive note, or serve a beverage unexpectedly for a family member today.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.BEGINNER,
    dailyTask: 'Execute one helpful or positive gesture for a loved one today.',
    benefits: ['Reduces household arguments', 'Models kindness and empathy', 'Spreads joy within the household', 'Builds cooperative dynamics'],
    safetyNote: 'Make gestures genuine and do not expect immediate rewards.',
    isPopular: false,
    isRecommended: true,
    categoryIdKey: 'family-wellness',
  },
  {
    title: 'Screen-Free Playtime',
    slug: 'screen-free-playtime',
    shortDescription: 'Spend 30 minutes of screen-free play with children or family.',
    description: 'Provide undivided attention. Dedicate 30 minutes to playing, talking, or creating art with family members without any devices visible.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.EASY,
    dailyTask: 'Complete 30 minutes of undivided device-free connection today.',
    benefits: ['Builds strong emotional security', 'Increases conversational vocabulary', 'Fosters collaborative creativity', 'Alleviates parents digital fatigue'],
    safetyNote: 'Focus entirely on the family; do not keep your phone on vibrate.',
    isPopular: false,
    isRecommended: false,
    categoryIdKey: 'family-wellness',
  },
  {
    title: 'Healthy Cookout Collaboration',
    slug: 'healthy-cookout-collaboration',
    shortDescription: 'Cook a new healthy recipe together once a week.',
    description: 'Make cooking a collaborative effort. Select a new nutritious, plant-based or whole-food meal, and prepare it together with your family.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.EASY,
    dailyTask: 'Prepare a healthy collaborative meal with family today.',
    benefits: ['Teaches children cooking skills', 'Explores new nutritional foods', 'Saves restaurant expenses', 'Encourages teamwork'],
    safetyNote: 'Supervise children strictly when sharp knives or hot stoves are involved.',
    isPopular: false,
    isRecommended: false,
    categoryIdKey: 'family-wellness',
  },
  {
    title: 'Bedtime Gratitude Circle',
    slug: 'bedtime-gratitude-circle',
    shortDescription: 'Share one thing you appreciate about each other before bed.',
    description: 'End the day with warmth. Establish a bedtime routine where family members share one specific reason they appreciate each other.',
    durationDays: 30,
    difficulty: ChallengeDifficulty.BEGINNER,
    dailyTask: 'Share a sincere note of appreciation with a family member tonight.',
    benefits: ['Alleviates sibling rivalry', 'Lowers stress hormones before sleeping', 'Strengthens self-worth in children', 'Creates a peaceful home environment'],
    safetyNote: 'Keep notes authentic, gentle, and positive.',
    isPopular: false,
    isRecommended: false,
    categoryIdKey: 'family-wellness',
  },
];
